<img src='./figures/logo-ecole-polytechnique-ve.jpg' style='position:absolute; top:0; right:0;' width='100px' height='' alt='' />

<center>**Bachelor of Ecole Polytechnique**</center>
<center>Computational Mathematics, year 2, semester 1</center>
<center>Lecturer: Lucas Gerin <a href="mailto:lucas.gerin@polytechnique.edu">(send mail)</a></center>

# Graphs and Matrices 3: Test

## Table of contents

- [Exercise 1: Letters $a$ come by two or three](#isolated)
- [Exercise 2: A coin game](#frog)
- [Exercise 3: Distinct colors](#color)
- [Exercise 4: Paths in a graph](#RW)



In [2]:
# execute this part to modify the css style
from IPython.core.display import HTML
def css_styling():
    styles = open("../style/custom2.css").read()
    return HTML(styles)
css_styling()


In [3]:
## loading python libraries

# necessary to display plots inline:
%matplotlib inline   

# load the libraries
import matplotlib.pyplot as plt # 2D plotting library
import numpy as np              # package for scientific computing  

from math import *              # package for mathematics (pi, arctan, sqrt, factorial ...)
import sympy as sympy             # package for symbolic computation
from sympy import *


<!--<div markdown=1 class="Rmk"> Here is the Latex code of a matrix that you can copy/paste throughout the notebook:
$$
M=
\begin{matrix}
v_1 \\ v_2 \\ v_3 
\end{matrix}
\begin{pmatrix}
1 & 1 & 0\\
0 & 0 & 1\\
0 & 1 & 0\\
\end{pmatrix}.
$$-->


<div markdown=1 class=Abstract>

# Please read!

#### Guidelines for graded notebooks

* This notebook is graded, you must submit your work (only the .pynb file) on the moodle at the end of the session.
* Submission is due at 5:35 pm. No late submission is permitted.
* The work is **individual**, you are not allowed to communicate with other students. Copy/pasting has been very severely punished in previous years.
* You are allowed to access previous notebooks and the lecture notes (and any online documentation on numpy, python,...).
* The four exercises are independent. You can of course solve the exercices in any order.
* **Each function or script must be tested** (for your sake, it also must be commented).
* Mathematical explanations have to be given in the corresponding "Answer" cell (not as comments of the code). Try to be rigorous and concise.
* Here is a sample of a matrix in LateX that you can copy/paste if needed:
$$
A=
\begin{matrix}
 u \\ v \\ w 
\end{matrix}
\begin{pmatrix}
0 & 1 & 0  \\
0 & 0 & 0\\
0 &  1 & 1\\
\end{pmatrix}.
$$


Here is a sample of a code to define a matrix in numpy and raise it to some power:

In [ ]:
TransitionMatrix=np.zeros([3,3])
for k in range(3):
    TransitionMatrix[k,k]=1/2
    TransitionMatrix[k,(k+1)%3]=1/2
print('A transition matrix M:')
print(TransitionMatrix)
print('M**4 =')
print(np.linalg.matrix_power(TransitionMatrix,4))
print('not to be confused with:')
print(TransitionMatrix**4)

A transition matrix M:
[[0.5 0.5 0. ]
 [0.  0.5 0.5]
 [0.5 0.  0.5]]
M**4 =
[[0.3125 0.3125 0.375 ]
 [0.375  0.3125 0.3125]
 [0.3125 0.375  0.3125]]
not to be confused with:
[[0.0625 0.0625 0.    ]
 [0.     0.0625 0.0625]
 [0.0625 0.     0.0625]]


<a id='isolated'></a>
## Exercise 1. Letters $a$ come by two or three

<div markdown=1 class="DoIt"> 

We consider words $w$ with letters $a,b$. We say that $w$ is <i>proper</i> if every run of consecutive $a$'s has length $2$ or $3$. For instance
$$
w_1=b\color{green}{aa}b\color{green}{aaa}bbbbbb\color{green}{aa}b
$$
is proper while
$$
w_2=\color{green}{aa}b\color{green}{aaa}b\color{red}{a}bbbbb\color{green}{aa}b\color{red}{aaaaa}
$$
is not.
Let $I_n$ be the number of proper words with $n$ letters.

Compute $I_{20}$ using a graph and its adjacency matrix. Explain carefully which graph and which coefficients of the matrix you consider.

<i>(To check your result: I find $I_{10}=104$.)</i>


<div markdown=1 class="Answers"> 
Your answer here.


In [ ]:
A = np.array([[1,1,0,0],
              [0,0,1,0],
              [1,0,0,1],
              [1,0,0,0]], dtype=int)

v0  = np.array([[1,0,0,0]])      # start in B
acc = np.array([[1,0,1,1]]).T    # accept B, A2, A3

def I_n(n):
    return int((v0 @ np.linalg.matrix_power(A, n) @ acc)[0,0])

print(I_n(10))  
print(I_n(20))  # 12816

NameError: name 'np' is not defined

<a id="frog"></a>
## Exercise 2: A coin game


A player is playing the following game of chance. She starts with an initial fortune of $0$, and at each step, she rolls a fair $6$-sided die. If the die lands on $6$, she loses. Otherwise, she adds the number to her fortune, and she continues. If her fortune reaches $10$ (or more) without rolling a $6$, she has won the game.

Here are two sample games:
\begin{align*}
&0 \stackrel{\text{die lands on }3}{\longrightarrow} 3 \stackrel{\text{die lands on }4}{\longrightarrow} 7
\stackrel{\text{die lands on }6}{\longrightarrow} \text{Lost}.\\
&0 \stackrel{\text{die lands on }5}{\longrightarrow} 5 \stackrel{\text{die lands on }2}{\longrightarrow} 7
\stackrel{\text{die lands on }1}{\longrightarrow} 8 \stackrel{\text{die lands on }4}{\longrightarrow} \text{Won}.
\end{align*}
Let also $T\in{1,2,3,\dots,10}$ be the random variable given by the number of rolls in a sample of the game. In the example above, $T=3$ and $T=4$ respectively.

<div markdown=1 class="DoIt"> 

1. Compute the probability $p$ that the player wins the game. (You can design a Markov chain on the set $\{0,1,2,\dots, 9,\text{Won},\text{Lost}\}$.)<br>
<i>(To check your code: you must find something very close to $1/2$.)</i>
2. Compute  $\mathbb{P}(T\leq 4)$. (Explain your strategy.)

<div markdown=1 class="Answers"> 

**Question 1.**<br>
<br>
<br>
**Question 2.** 

In [ ]:

import numpy as np

# State order: 0,1,2,3,4,5,6,7,8,9, Won, Lost  (total 12)
N_TRANS = 10
N_ABS = 2
N = N_TRANS + N_ABS
WON, LOST = N_TRANS, N_TRANS + 1

P = np.zeros((N, N), dtype=float)

# Build transitions from transient states
for s in range(N_TRANS):
    # Roll a 6 -> Lost
    P[s, LOST] += 1/6
    # Rolls 1..5
    for k in range(1, 6):
        if s + k >= 10:
            P[s, WON] += 1/6
        else:
            P[s, s + k] += 1/6

# Absorbing states
P[WON, WON] = 1.0
P[LOST, LOST] = 1.0

# Extract Q and R
Q = P[:N_TRANS, :N_TRANS]
R = P[:N_TRANS, N_TRANS:]

# 1) Probability of eventually winning (absorbing probs): B = (I - Q)^{-1} R
I = np.eye(N_TRANS)
Nmat = np.linalg.inv(I - Q)  # fundamental matrix
B = Nmat @ R                 # absorption probabilities into [Won, Lost]

p_win = B[0, 0]  # from state 0 into Won
p_lose = B[0, 1]

# 2) P(T <= 4) via surviving mass after 4 steps among transients
e0 = np.zeros((N_TRANS,))
e0[0] = 1.0         # start at sum=0
Q4 = np.linalg.matrix_power(Q, 4)
still_playing_after_4 = e0 @ Q4 @ np.ones((N_TRANS,))
p_T_le_4 = 1.0 - still_playing_after_4

print(f"Winning probability p = {p_win:.10f}")
print(f"Losing probability    = {p_lose:.10f}  (sanity: p+q={p_win+p_lose:.10f})")
print(f"P(T <= 4)             = {p_T_le_4:.10f}")

# Optional: cross-check: simulate the dynamic recursion for p_s (not required)
# to see the known exact value ~0.509065448 and P(T<=4) ~0.905864198.


<a id='color'></a>
## Exercise 3. Distinct colors.

<div markdown=1 class="DoIt"> 
A urn contains seven balls, one of each color: Black, White, Red, Green, Blue, Yellow, Purple. At times $1,2,3,\dots$ a ball is drawn uniformly at random and put back into the urn.

<b>Question 1</b>. Let $E_n$ be the event
$$
\{\text{ At least $4$ distinct colors have been seen at time }n\ \}.
$$
Of course $\mathbb{P}(E_1)=\mathbb{P}(E_2)=\mathbb{P}(E_3)=0$. You can check that $\mathbb{P}(E_4)=0.34985...$

Write a function which computes $\mathbb{P}(E_n)$ (explain carefully your method). Plot $n\mapsto \mathbb{P}(E_n)$.

<i>(Hint: you can consider a Markov chain on the set $\{0\text{ color}$, $1\text{ color already seen}$, $2\text{ colors already seen}$, $3\text{ colors already seen}$, $4\text{ colors or more already seen}\}$.)</i>

<b>Question 2</b>. Find the minimal $n$ such that $E_n$ occurs with more than $99\%$ chance.


A = np.zeros([7, 7])
k culori deja vazute, inseamna ca probabilitatea sa vezi una noua e n - k / n

<div markdown=1 class="Answers"> 

**Question 1.**<br>
<br>
<br>
**Question 2.** 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

def transition_matrix_atleast4(num_colors=7, threshold=4):
    s = threshold + 1
    T = np.zeros((s, s), dtype=float)
    for k in range(threshold):  # k = 0,1,2,3
        T[k, k] = k / num_colors
        T[k, min(k + 1, threshold)] = (num_colors - k) / num_colors
    T[threshold, threshold] = 1.0  # absorbing
    return T

def prob_E_n(n, num_colors=7, threshold=4):
    """
    Return P(E_n): probability that at least 'threshold' distinct colors
    have been seen after n draws (with replacement) from 'num_colors' colors.
    """
    T = transition_matrix_atleast4(num_colors, threshold)
    p0 = np.zeros(threshold + 1)
    p0[0] = 1.0
    pn = p0 @ np.linalg.matrix_power(T, n)
    return float(pn[threshold])

def minimal_n_for_threshold(q=0.99, num_colors=7, threshold=4, max_n=1000):
    """
    Return the smallest n such that P(E_n) > q.
    """
    T = transition_matrix_atleast4(num_colors, threshold)
    p = np.zeros(threshold + 1)
    p[0] = 1.0
    for n in range(max_n + 1):
        if p[threshold] > q:
            return n, float(p[threshold])
        p = p @ T
    return None, None

if __name__ == "__main__":
    # Example: verify the check for n=4
    print("P(E_4) =", prob_E_n(4))  # ≈ 0.349854...

    # Compute and plot P(E_n) for n=0..40
    NMAX = 40
    ns = np.arange(NMAX + 1)
    vals = [prob_E_n(n) for n in ns]

    plt.figure()
    plt.plot(ns, vals, marker='o')
    plt.xlabel('n (number of draws)')
    plt.ylabel('P(E_n)  [≥ 4 distinct colors by time n]')
    plt.title('7-color urn: probability of seeing ≥4 colors by time n')
    plt.grid(True)
    plt.show()

    # Find minimal n with probability > 99%
    n_min, p_at_n = minimal_n_for_threshold(0.99)
    print(f"Minimal n with P(E_n) > 0.99: n = {n_min}, P(E_n) = {p_at_n}")


<a id='RW'></a>

## Exercise 4: Paths in a windmill

For $n\geq 1$, we define the <i>$n$-bladed windmill</i> as the graph with vertex set $\{v_0,v_1,\dots,v_{2n}\}$ in which:
* $v_0$ is connected through an edge to every other vertex;
* for every even $1\leq i\leq 2n$, the vertex $v_i$ is connected to $v_0$ and $v_{i-1}$;
* for every odd $1\leq i\leq 2n$, the vertex $v_i$ is connected to $v_0$ and $v_{i+1}$.


Here is a picture of the $n$-bladed windmill for $n=6$:
<img src="figures/Windmill.jpg" style="width: 450px;"/>


<div markdown=1 class="DoIt"> 

For $n=50$, compute the number of paths starting at $v_0$ and ending at $v_0$ of length $10$ in the $n$-bladed windmill. Explain clearly the strategy.<br>
<i>(For $n=5$ you should find $215710$ paths of length $10$.)</i>

<div markdown=1 class="Answers"> 

Explain here your strategy.


<div markdown=1 class="DoIt"> 

We also fix $n=50$. Let $a_k$ be the number of paths of length $k$ in the $n$-bladed windmill, starting from $v_0$. Prove that there exist two constant $c,C>1$ such that 
$$
c^k \leq a_k \leq C^k.
$$

<div markdown=1 class="Answers"> 



In [ ]:
import numpy as np

def windmill_adjacency(n: int) -> np.ndarray:
    """Adjacency matrix A for the n-bladed windmill on vertices v0..v_{2n}."""
    m = 2*n + 1
    A = np.zeros((m, m), dtype=np.int64)

    # Hub v0 connected to all leaves
    for i in range(1, 2*n + 1):
        A[0, i] = A[i, 0] = 1

    # Blade edges: (v_{2j-1}, v_{2j}) for j=1..n
    for i in range(1, 2*n + 1):
        if i % 2 == 0:
            A[i, i-1] = A[i-1, i] = 1
        else:
            if i + 1 <= 2*n:
                A[i, i+1] = A[i+1, i] = 1
    return A

def closed_walks_length_k(n: int, k: int) -> int:
    """Number of length-k walks from v0 to v0 in the n-bladed windmill."""
    A = windmill_adjacency(n)
    Ak = np.linalg.matrix_power(A, k)
    return int(Ak[0, 0])

# Sanity check (given): n=5, k=10 -> 215710
print("n=5, length 10:", closed_walks_length_k(5, 10))

# Requested: n=50, length 10
print("n=50, length 10:", closed_walks_length_k(50, 10))
